//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedeath
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int idPers { get; set; }
        public string login { get; set; }
        public int pass { get; set; }
        public int idRole { get; set; }
        public string email { get; set; }
        public string checkCode { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual MC MC { get; set; }
    }
}
