//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedeath
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int idRew { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string text { get; set; }
    }
}
