//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedeath
{
    using System;
    using System.Collections.Generic;
    
    public partial class sa
    {
        public int idSS { get; set; }
        public int idPers { get; set; }
        public int idA { get; set; }
    
        public virtual ach ach { get; set; }
        public virtual MC MC { get; set; }
    }
}
