//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedeath
{
    using System;
    using System.Collections.Generic;
    
    public partial class timet
    {
        public int idTT { get; set; }
        public Nullable<int> idPers { get; set; }
        public Nullable<int> idQ { get; set; }
        public Nullable<int> process { get; set; }
    
        public virtual MC MC { get; set; }
        public virtual quest quest { get; set; }
    }
}
